# Generated by Django 3.0.3 on 2020-09-28 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('prescription', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/medical-docs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('alt_phone', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('fax_phone', models.CharField(blank=True, max_length=12, unique=True)),
                ('address', models.CharField(max_length=1024, verbose_name='address')),
                ('city', models.CharField(default='', max_length=64, verbose_name='city')),
                ('state', localflavor.us.models.USStateField(default='AL', max_length=2, verbose_name='state')),
                ('zip_code', models.CharField(default='', max_length=5, verbose_name='zip code')),
                ('specialty', models.CharField(choices=[('AI', 'ALLERGY & IMMUNOLOGY'), ('AN', 'ANESTHESIOLOGY'), ('DE', 'DERMATOLOGY'), ('DR', 'DIAGNOSTIC RADIOLOGY'), ('EM', 'EMERGENCY MEDICINE'), ('FM', 'FAMILY MEDICINE'), ('IM', 'ITERNAL MEDICINE'), ('MG', 'MEDICAL GENETICS'), ('NEURO', 'NEUROLOGY'), ('NM', 'NUCLEAR MEDICINE'), ('OBGYN', 'OBSTETRICS AND GYNECOLOGY'), ('OP', 'OPHTHALMOLOGY'), ('PATHO', 'PATHOLOGY'), ('PED', 'PEDIATRICS'), ('PHYS', 'PHYSICAL MEDICINE & REHABILITATION'), ('PM', 'PREVENTIVE MEDICINE'), ('PSYCH', 'PSYCHIATRY'), ('RO', 'RADIATION ONCOLOGY'), ('SUR', 'SURGERY'), ('URO', 'UROLOGY')], default='AI', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
