# Generated by Django 3.0.3 on 2020-09-26 21:43

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('fax_phone', models.CharField(blank=True, max_length=12, unique=True)),
                ('address', models.CharField(max_length=1024, verbose_name='address')),
                ('city', models.CharField(default='', max_length=64, verbose_name='city')),
                ('state', localflavor.us.models.USStateField(default='AL', max_length=2, verbose_name='state')),
                ('zip_code', models.CharField(default='', max_length=5, verbose_name='zip code')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('alt_phone', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/medical-docs')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('prescription', models.TextField()),
            ],
        ),
    ]
