# Generated by Django 3.0.3 on 2020-09-28 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorcontact',
            name='specialty',
        ),
    ]
