# Generated by Django 3.0.3 on 2020-09-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_doctorcontact_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcontact',
            name='specialty',
            field=models.CharField(choices=[('AI', 'ALLERGY & IMMUNOLOGY'), ('AN', 'ANESTHESIOLOGY'), ('DE', 'DERMATOLOGY'), ('DR', 'DIAGNOSTIC RADIOLOGY'), ('EM', 'EMERGENCY MEDICINE'), ('FM', 'FAMILY MEDICINE'), ('IM', 'ITERNAL MEDICINE'), ('MG', 'MEDICAL GENETICS'), ('NEURO', 'NEUROLOGY'), ('NM', 'NUCLEAR MEDICINE'), ('OBGYN', 'OBSTETRICS AND GYNECOLOGY'), ('OP', 'OPHTHALMOLOGY'), ('PATHO', 'PATHOLOGY'), ('PED', 'PEDIATRICS'), ('PHYS', 'PHYSICAL MEDICINE & REHABILITATION'), ('PM', 'PREVENTIVE MEDICINE'), ('PSYCH', 'PSYCHIATRY'), ('RO', 'RADIATION ONCOLOGY'), ('SUR', 'SURGERY'), ('URO', 'UROLOGY')], default='AI', max_length=255),
        ),
    ]
