# Generated by Django 3.0.3 on 2020-09-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20200926_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
